insert into clientes(nombre, apellido, email, create_at, foto) values('Kokomi', 'Teruhashi', 'terukoko@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Chisato', 'Chiyou', 'chisato@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Kokomi', 'Teruhashi', 'terukoko@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Chisato', 'Chiyou', 'chisato@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Kokomi', 'Teruhashi', 'terukoko@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Chisato', 'Chiyou', 'chisato@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Kokomi', 'Teruhashi', 'terukoko@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Chisato', 'Chiyou', 'chisato@gmail.com', '2021-01-01', '');
insert into clientes(nombre, apellido, email, create_at, foto) values('Kokomi', 'Teruhashi', 'terukoko@gmail.com', '2021-01-01', '');